//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Sonic.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data.Linq;
using System.Linq;
using FoodTrade.Entity;
using FoodTrade.DAL;

namespace FoodTrade.BLL.Component
{
	public partial class SupplierProductBLL
	{
		public void Create(SupplierProductEntity item)
		{
			using (var context = new DatabaseContext())
			{
				var e = new SupplierProduct();
				e.SupplierID = item.SupplierID;
				e.ProductID = item.ProductID;
				e.Stock = item.Stock;
				e.SRP = item.SRP;
				e.Status = item.Status;
				e.CreatedBy = item.CreatedBy;
				e.CreatedDate = item.CreatedDate;
				e.ModifiedBy = item.ModifiedBy;
				e.ModifiedDate = item.ModifiedDate;
				context.SupplierProducts.Add(e);
				context.SaveChanges();

				item.ID = e.ID;
			}
		}

		public void Update(SupplierProductEntity item)
		{
			using (var context = new DatabaseContext())
			{
				var e = context.SupplierProducts.SingleOrDefault(o => o.ID == item.ID);

				if (e != null)
				{
					e.SupplierID = item.SupplierID;
					e.ProductID = item.ProductID;
					e.Stock = item.Stock;
					e.SRP = item.SRP;
					e.Status = item.Status;
					e.CreatedBy = item.CreatedBy;
					e.CreatedDate = item.CreatedDate;
					e.ModifiedBy = item.ModifiedBy;
					e.ModifiedDate = item.ModifiedDate;
					context.SaveChanges();
				}
			}
		}

		public void Delete(int id)
		{
			using (var context = new DatabaseContext())
			{
				var e = context.SupplierProducts.SingleOrDefault(o => o.ID == id);

				if (e != null)
				{
					context.SupplierProducts.Remove(e);
					context.SaveChanges();
				}
			}
		}

		public SupplierProductEntity Get(int id)
		{
			using (var context = new DatabaseContext())
			{
				var item = context.SupplierProducts.SingleOrDefault(o => o.ID == id);

				if (item != null)
				{
					return MapFields(item);
				}

				return null;
			}
		}

		public List<SupplierProductEntity> GetAll()
		{
			using (var context = new DatabaseContext())
			{
				var items = context.SupplierProducts.Where(o => 1 == 1);
				var models = new List<SupplierProductEntity>();

				foreach (var item in items)
				{
					models.Add(MapFields(item));
				}

				return models;
			}
		}

		public static SupplierProductEntity MapFields(SupplierProduct item)
		{
			return new SupplierProductEntity
			{
				ID = item.ID,
				SupplierID = item.SupplierID,
				ProductID = item.ProductID,
				Stock = item.Stock,
				SRP = item.SRP,
				Status = item.Status,
				CreatedBy = item.CreatedBy,
				CreatedDate = item.CreatedDate,
				ModifiedBy = item.ModifiedBy,
				ModifiedDate = item.ModifiedDate
			};
		}

	}
}
