//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Sonic.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using FoodTrade.BLL.Component;

namespace FoodTrade.BLL
{
	public partial class BusinessFacade
	{
		public static readonly ConsumerBLL Consumer = new ConsumerBLL();
		public static readonly ProductBLL Product = new ProductBLL();
		public static readonly SupplierBLL Supplier = new SupplierBLL();
		public static readonly SupplierProductBLL SupplierProduct = new SupplierProductBLL();
	}
}
